import React from 'react'
import styles from "../styles/Landing.module.css"
import Image from "next/image"
import pimg from "../public/assets/mobport.svg"
import pimg2 from "../public/assets/tamalport1.png"
import Navbar from '../components/Navbar'
import Link from 'next/link'
import Head from "next/head"
import tdabt from "../public/assets/tdabt.png"

const about = () => {
    return (
        <div className={styles.parent}>

            <Head>
                <title>Portfolio | About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.navbardiv}>
                <Navbar />
            </div>

            <div className={`container ${styles.parentDesktop}`}>
                <div className="row">


                    <div className={`col-4`}>
                        <div className={styles.landing_imgdiv}>


                            <Image src={tdabt} width={350} height={350} alt="portfolio" className={styles.portfolioimg} />



                        </div>
                    </div>

                    <div className={`col-8`}>
                        <div className={styles.landingheydesktop}>

                            <div className={styles.landing_navbar}>
                                <Link href={"/projects"} ><p className={styles.navlink1}>Projects</p></Link>
                                <Link href={"/about"} ><p className={styles.navlink2}>About me</p></Link>
                                <Link href={"/contact"} ><p className={styles.navlink3}>Contact me</p></Link>

                            </div>

                            <p className={styles.landing_heythere}>Here&apos;s all, <br /> about me</p>

                            <p className={styles.landing_heythere2}>I am Tamal Das , a sophomore pursuing BTech in CSE from UEMk. I am 20 years old , in love with developing new products and being active in all dev communities.

                                I love watching animes, travelling to places and just spending time with friends and families !!  </p>


                        </div>
                    </div>



                </div>
            </div>










            <div className={styles.landing_imgdiv2}>

                <p className={styles.landing_heythere}>Hey there, <br /> I&apos;m Tamal</p>

                <p className={styles.landing_heythere2}>I design beautifully simple things, <br /> And I love what i do.</p>

                <Image src={pimg} width={350} height={350} alt="twitterdp" className={styles.portfolioimg_mob} />



            </div>





        </div>
    )
}

export default about