import React from 'react'
import Head from "next/head";

const contact = () => {
    return (

        <>

            <Head>
                <title>Portfolio | Contact</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div>contact</div>
        </>

    )
}

export default contact