import React from 'react'
import Head from "next/head";

const projects = () => {
    return (
        <>
            <Head>
                <title>Portfolio | Projects</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div>about</div>

        </>
    )
}

export default projects